version: "3"
services:
  # container do servidor web
  apache:
    image: php:7.4-apache
    container_name: apache
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    restart: always
    ports:
      - 8085:80
    volumes:
      - ./www/html:/var/www/html
      - ./etc/apache2/sites-available/:/etc/apache2/sites-available/
      - ./etc/php/7.2/apache/:/etc/php/7.2/apache/