version: "3.3"
services:
  web_server:
    image: thecodingmachine/php:7.2-v3-apache
    container_name: sonda-webserver
    environment:
      PHP_EXTENSIONS: intl
    build: .
    volumes:
      - ./www/html/:/var/www/html/
      - ./etc/apache2/sites-available/:/etc/apache2/sites-available/
    restart: always
    ports:
      - 8080:80